_format_version: "2.1"
_transform: true

services:
  - name: auth-v1
    url: http://supabase-auth:9999
    routes:
      - name: auth-v1-route
        paths:
          - /auth/v1
    plugins:
      - name: cors

  - name: rest-v1
    url: http://supabase-rest:3000
    routes:
      - name: rest-v1-route
        paths:
          - /rest/v1
    plugins:
      - name: cors

  - name: storage-v1
    url: http://supabase-storage:5000
    routes:
      - name: storage-v1-route
        paths:
          - /storage/v1
    plugins:
      - name: cors

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
        - X-Auth-Token
        - apikey
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600 